name: Bug report
description: Report bug
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling this report bug form!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened.
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happend?
      description: Describe what should happen.
    validations:
      required: true
